# Generated by Django 4.2.5 on 2023-09-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0003_term_culinary_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['id'], 'verbose_name': 'Аллерген', 'verbose_name_plural': 'Аллергены'},
        ),
        migrations.AlterModelOptions(
            name='culinary',
            options={'ordering': ['id'], 'verbose_name': 'Тип меню', 'verbose_name_plural': 'Тип меню'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['discount'], 'verbose_name': 'Срок подписки', 'verbose_name_plural': 'Срок подписки'},
        ),
    ]
