# Generated by Django 4.2.5 on 2023-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0004_alter_allergen_options_alter_culinary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('BR', 'Завтрак'), ('LN', 'Обед'), ('DN', 'Ужин'), ('DS', 'Десерт')], default='BR', max_length=2, verbose_name='Тип блюда'),
        ),
    ]
